import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { nanoid } from 'nanoid';

// Define the Contact interface
interface Contact {
  id: string;
  firstName: string;
  lastName: string;
  status: 'active' | 'inactive';
}

// Define the initial state interface
interface ContactsState {
  contacts: Contact[];
}

// Initialize the state with an empty contacts array
const initialState: ContactsState = {
  contacts: [],
};

// Create the slice
const contactsSlice = createSlice({
  name: 'contacts', // Name of the slice
  initialState, // Initial state
  reducers: {
    // Reducer to add a contact
    addContact: {
      reducer: (state, action: PayloadAction<Contact>) => {
        state.contacts.push(action.payload); // Add the new contact to the state
      },
      prepare: (firstName: string, lastName: string, status: 'active' | 'inactive') => ({
        payload: {
          id: nanoid(), // Generate a unique ID using nanoid
          firstName,
          lastName,
          status,
        },
      }),
    },
    // Reducer to delete a contact by ID
    deleteContact: (state, action: PayloadAction<string>) => {
      state.contacts = state.contacts.filter(contact => contact.id !== action.payload);
    },
    // Reducer to update a contact
    updateContact: (state, action: PayloadAction<Contact>) => {
      const index = state.contacts.findIndex(contact => contact.id === action.payload.id);
      if (index !== -1) {
        state.contacts[index] = action.payload; // Update the contact if found
      }
    },
    // Reducer to load contacts from local storage
    setContactsFromLocalStorage: (state) => {
      const savedContactsJSON = localStorage.getItem('contacts');
      if (savedContactsJSON) {
        state.contacts = JSON.parse(savedContactsJSON); // Parse and set the contacts from local storage
      }
    },
  },
});

// Export the actions generated by createSlice
export const { addContact, deleteContact, updateContact, setContactsFromLocalStorage } = contactsSlice.actions;

// Export the reducer to be used in the store
export default contactsSlice.reducer;

// Export the Contact type for use in other parts of the app
export type { Contact };
